# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  SWAPFILE_SIZE: 2G
  SWAPFILE_NAME: /swapfile

tasks:
  install:
    desc: Indstall k3s
    cmds:
      - curl -sfL https://get.k3s.io | sh -

  init:
    desc: Use kubectl without sudo
    cmds:
      - mkdir ~/.kube 2> /dev/null
      - sudo k3s kubectl config view --raw > "$KUBECONFIG"
      - chmod 600 "$KUBECONFIG"

  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get all -n kube-system

  swapfile:
    desc: Add {{.SWAPFILE_SIZE}} swapfile at {{.SWAPFILE_NAME}} (optional)
    cmds:
      - sudo fallocate -l "{{.SWAPFILE_SIZE}}" "{{.SWAPFILE_NAME}}"
      - sudo mkswap "{{.SWAPFILE_NAME}}"
      - sudo swapon "{{.SWAPFILE_NAME}}"
      - echo '"{{.SWAPFILE_NAME}}" none swap sw 0 0' | sudo tee -a /etc/fstab
      - sudo sysctl vm.swappiness=10
      - echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf

  uninstall:
    desc: Uninstall k3s
    cmds:
      - k3s-uninstall.sh
