apiVersion: v1
kind: PersistentVolume
metadata:
  name: wg-easy-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${WG_DATA}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${HOSTNAME}
