apiVersion: v1
kind: PersistentVolume
metadata:
  name: wg-easy-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${WG_DATA}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${HOSTNAME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-storage-claim
  namespace: wg-easy
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  volumeName: wg-easy-pv
  resources:
    requests:
      storage: 256Mi
