# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  ADMIN_EMAIL_VAR: wuhanstudio@qq.com
  ROOT_DOMAIN_VAR: wuhanstudio.click
  WHOAMI_NAME_VAR: whoamik

env:
  ADMIN_EMAIL: '{{.ADMIN_EMAIL_VAR}}'
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  install:
    desc: Install cert-manager
    cmds:
      - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml

  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get all -n cert-manager

  letsencrypt:
    desc: Use letsencrypt for cert-manager
    cmds:
      - envsubst < letsencrypt-prod.yml | kubectl apply -f -

  whoami-tls:
    desc: Install tls certificate for whoami application
    env:
        WHOAMI_NAME: '{{.WHOAMI_NAME_VAR}}'
    cmds:
      - envsubst < whoami-tls-ingress.yml | kubectl apply -f -

  whoami-cert:
    desc: Check the certificate of whoami application
    cmds:
      - kubectl describe secret whoami-tls
