
version: '3'

vars:
  ROOT_DOMAIN_VAR: wuhanstudio.click
  ACME_PATH_VAR:   /data/acme

env:
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get ingress
      - kubectl logs deployment.apps/traefik -n kube-system
      - kubectl exec -n kube-system deploy/traefik -- cat {{.ACME_PATH_VAR}}/acme.json | grep {{.ROOT_DOMAIN_VAR}}

  womginx:
    desc: Deploy maze application at maze.{{.ROOT_DOMAIN_VAR}}
    cmds:
      - kubectl apply -f womginx-app.yml
      - envsubst < womginx-ingress.yml | kubectl apply -f -

  womginx-tls:
    desc: Install tls certificate for womginx application
    cmds:
      - envsubst < womginx-tls-ingress.yml | kubectl apply -f -

