
version: '3'

vars:
  ROOT_DOMAIN_VAR: wuhanstudio.click
  WHOAMI_NAME_VAR: whoami
  ACME_PATH_VAR:   /data/acme

env:
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get ingress
      - kubectl logs deployment.apps/traefik -n kube-system
      - kubectl exec -n kube-system deploy/traefik -- cat {{.ACME_PATH_VAR}}/acme.json | grep {{.ROOT_DOMAIN_VAR}}

  whoami:
    desc: Deploy whoami application at {{.WHOAMI_NAME_VAR}}.{{.ROOT_DOMAIN_VAR}}
    env:
      WHOAMI_NAME: '{{.WHOAMI_NAME_VAR}}'
    cmds:
      - kubectl apply -f whoami-app.yml
      - envsubst < whoami-ingress.yml | kubectl apply -f -

  whoami-tls:
    desc: Install tls certificate for whoami application
    env:
        WHOAMI_NAME: '{{.WHOAMI_NAME_VAR}}'
    cmds:
      - envsubst < whoami-tls-ingress.yml | kubectl apply -f -

