
version: '3'

vars:
  ADMIN_EMAIL_VAR: wuhanstudio@qq.com
  ROOT_DOMAIN_VAR: wuhanstudio.click
  WHOAMI_NAME_VAR: whoamik

env:
  ADMIN_EMAIL: '{{.ADMIN_EMAIL_VAR}}'
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  status:
    desc: Check installation status
    cmds:
      - kubectl get all

  whoami-tls:
    desc: Install tls certificate for whoami application
    env:
        WHOAMI_NAME: '{{.WHOAMI_NAME_VAR}}'
    cmds:
      - envsubst < whoami-tls-ingress.yml | kubectl apply -f -

  whoami-cert:
    desc: Check the certificate of whoami application
    cmds:
      - kubectl describe secret whoami-tls
