
version: '3'

vars:
  ADMIN_EMAIL_VAR: wuhanstudio@qq.com
  ROOT_DOMAIN_VAR: wuhanstudio.click
  WHOAMI_NAME_VAR: whoami
  ACME_PATH_VAR:   /data/acme

env:
  ADMIN_EMAIL: '{{.ADMIN_EMAIL_VAR}}'
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get ingress
      - kubectl logs deployment.apps/traefik -n kube-system
      - kubectl exec -n kube-system deploy/traefik -- cat {{.ACME_PATH_VAR}}/acme.json | grep {{.ROOT_DOMAIN_VAR}}

  whoami-tls:
    desc: Install tls certificate for whoami application
    env:
        WHOAMI_NAME: '{{.WHOAMI_NAME_VAR}}'
    cmds:
      - envsubst < whoami-tls-ingress.yml | kubectl apply -f -

