server {
    listen       80;
    server_name  _;
    
    error_page 404 /404.html;

    # other error pages here:
    # error_page  403    /404.html;

    # All requests -> custom 404 page
    location / {
        root  /usr/share/nginx/html;
        internal;
    }
}
